<a href="https://colab.research.google.com/github/Akash-Adak/Machine-Learning/blob/f1/SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



## 🧠 Support Vector Machine (SVM) – Full Theory

### 📌 What is SVM?
Support Vector Machine (SVM) is a powerful supervised learning algorithm primarily used for classification tasks, though it can also handle regression. It aims to find the best decision boundary (called a *hyperplane*) that separates different classes in the feature space.

---

### ✒️ Key Concepts

- **Hyperplane**: A decision boundary that separates classes. In 2D, it's a line; in 3D, it's a plane; in higher dimensions, it's a hyperplane.
- **Support Vectors**: Data points closest to the hyperplane. These are critical for defining the margin and the optimal hyperplane.
- **Margin**: The distance between the hyperplane and the support vectors. SVM tries to maximize this margin for better generalization.
- **Kernel Trick**: A technique to transform data into higher dimensions to make it linearly separable. Common kernels:
  - *Linear*: For linearly separable data.
  - *Polynomial*: For curved boundaries.
  - *RBF (Radial Basis Function)*: For complex, non-linear boundaries.
  - *Sigmoid*: Similar to neural networks.

---

### ⚙️ How SVM Works

1. **Input**: Labeled training data.
2. **Objective**: Find the hyperplane that best separates the classes.
3. **Optimization**: Maximize the margin while minimizing classification error.
4. **Prediction**: Classify new data based on which side of the hyperplane it falls.

---

### 📐 Mathematical Formulation

image.png- For a linear SVM, the hyperplane is defined as:  
  \[
  \mathbf{w} \cdot \mathbf{x} + b = 0
  \]
- The optimization problem:
  \[
  \min_{\mathbf{w}, b} \frac{1}{2} \|\mathbf{w}\|^2 \quad \text{subject to} \quad y_i(\mathbf{w} \cdot \mathbf{x}_i + b) \geq 1
  \]
- For non-linear data, kernels are used to compute dot products in transformed space without explicitly transforming the data.

---

### ✅ Advantages of SVM

- Effective in high-dimensional spaces.
- Works well with clear margin of separation.
- Memory efficient (uses support vectors only).
- Versatile with different kernel functions.

---

### ❌ Limitations

- Not suitable for large datasets due to high training time.
- Performance drops when classes overlap heavily.
- Requires careful tuning of kernel and regularization parameters.

---

### 📊 Applications

- Text classification (spam detection, sentiment analysis)
- Image recognition
- Bioinformatics (gene classification)
- Handwriting digit recognition

---

### 📚 Summary

SVM is a robust and versatile algorithm that excels in classification tasks with clear boundaries. Its ability to use kernels makes it powerful for non-linear problems. However, it requires careful preprocessing and parameter tuning for optimal performance.

---



In [2]:
# Import necessary libraries
import numpy as np                      # For numerical operations
import matplotlib.pyplot as plt         # For plotting (not used here but useful for visualization)
from sklearn.datasets import load_iris # Load the Iris dataset
from sklearn.model_selection import train_test_split # Split data into training and testing sets
from sklearn.svm import SVC             # Support Vector Machine classifier
from sklearn.preprocessing import StandardScaler     # Standardize features
from sklearn.metrics import classification_report, confusion_matrix # Evaluate model performance

# Load the Iris dataset
iris = load_iris()                      # iris.data contains features, iris.target contains labels
x = iris.data                           # Feature matrix: sepal/petal length and width
y = iris.target                         # Target vector: species labels (0=setosa, 1=versicolor, 2=virginica)

# Split the dataset into training and testing sets (70% train, 30% test)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

# Standardize the feature values for better SVM performance
scaler = StandardScaler()              # Create a scaler object
x_train = scaler.fit_transform(x_train) # Fit scaler on training data and transform it
x_test = scaler.transform(x_test)       # Transform test data using the same scaler

# Initialize and train the SVM model with a linear kernel
svm_model = SVC(kernel='linear', C=1)   # C=1 is the regularization parameter
svm_model.fit(x_train, y_train)         # Train the model on the scaled training data

# Make predictions on the test set
y_pred = svm_model.predict(x_test)      # Predict the species for test data

# Print evaluation metrics
print("\nClassification Report:\n", classification_report(y_test, y_pred)) # Precision, recall, F1-score
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))             # Matrix of actual vs predicted labels



Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.92      0.96        13
           2       0.93      1.00      0.96        13

    accuracy                           0.98        45
   macro avg       0.98      0.97      0.97        45
weighted avg       0.98      0.98      0.98        45

Confusion Matrix:
 [[19  0  0]
 [ 0 12  1]
 [ 0  0 13]]
